name: Populate Project
description: Create GitHub project, columns, and issues based on external input
inputs:
  config-dir:
    description: Path to directory containing config.yml file
    default: .github/populate_project
    required: true
  debug:
    description: Boolean whether to log debug information
    default: "false"
    required: true
  fail-fast:
    description: Boolean whether to fail if any project fails to be created
    default: "false"
    required: true
  github-token:
    description: GitHub personal access token used for API interactions
    required: true
runs:
  using: node12
  main: index.js