projects:
  - name: Example Engagement
    body: |
      This is a project board that might be created for a customer engagement.

    columns:
      - Backlog
      - To Do
      - In Progress
      - Done

    issues:
      - title: |
          Backlog item
        body: |
          Stubbed text for generic backlog issue.

      - column: To Do
        title: |
          {{ github.payload.inputs.customer_name }} introduction
        body: |
          This should be an introduction with {{ github.payload.inputs.customer_name }}.

  - name: Another Example
    body: |
      Stub description of project.

    columns:
      - A
      - B
      - C